### ISSUE TITLE
Gtk Theme parsing errors

### ISSUE THREAD

**Issue by Sadi58** [killhellokitty/DeLorean-3.16#1]
FYI when I enter the command "nautilus -q" in a terminal screen I see the following error messages:

```
(nautilus:10389): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2863:31: Missing name of pseudo-class

(nautilus:10389): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2866:33: Missing name of pseudo-class

(nautilus:10389): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2871:33: Missing name of pseudo-class

(nautilus:10389): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2874:33: Missing name of pseudo-class

(nautilus:10389): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2877:33: Missing name of pseudo-class
```

**Comment by killhellokitty** [comment]
Those lines have new functions for gtk-3.16 ie ':not(.hovering)'.  IF the scrollbars work fine in Ubuntu then you must ignore these errors.

**Comment by Sadi58** [comment]
Sorry, I forgot again that I'm trying to use this theme under GTK 3.14, which is probably the reason why I see these. Otherwise no problem with scrollbars.

**Comment by killhellokitty** [comment]
I just uploaded a corrected Ubuntu_styles.css and Unity.css to
DeLorean-3.14 I also made new Unity icons for it.  Give it a tr and see if
it helps.  I will look into your other posts as well.

**Comment by Sadi58** [comment]
Thanks, but it seems something went wrong with the git update: the sub-folder `https://github.com/killhellokitty/delorean/tree/master/gtk-3.0` is still empty.

**Comment by killhellokitty** [comment]
I am not using the git for the gtk-3.14 packages.  You will  need to
download from deviantart.com.   I still have a few of your issues to work
out but this version I believe is a definate improvement.

**Comment by Sadi58** [comment]
OK, thanks, I'll keep an eye on devianart then.
And it's already a definite improvement for sure; thanks :-)
