### ISSUE TITLE
See-through menus in Firefox on Fedora 22 beta

### ISSUE THREAD

**Issue by aiguofer** [killhellokitty/DeLorean-3.16#2]
Hey, thanks again for all your work!

I'm having this strange problem where the menu is see-through and unstyled input boxes have no border. The strange part is that this only happens in my fedora box, but it works fine in Arch.

Got any ideas?
![Uploading IMG_20150520_212902815.jpg…]()

**Comment by aiguofer** [comment]
![img_20150520_212902815](https://cloud.githubusercontent.com/assets/780934/7740540/26703602-ff41-11e4-8509-bfedbe38cd84.jpg)

**Comment by killhellokitty** [comment]
are you using the Firefox theme included in the theme package?  That may fix the issue as it has no transparency enabled within it.  Please let me know if that helps.

**Comment by aiguofer** [comment]
Yep, I'm using the Firefox theme. If I stop using it, the borders around input boxes and buttons comes back but the menu is still see-through.

**Comment by killhellokitty** [comment]
find the MENU section around line #2390 and change the .menu
background-color to: rgb(0,19,31)
See if that makes a differance.  IF not it must have something to do with
backdrop transparency.  I Use ARCH so I can't really say what is going on
with Fedora, but it sounds stange.   Let me know if that helps.

**Comment by aiguofer** [comment]
I assume you were talking about gtk-3.0/gtk-contained.css? Unfortunately it has no effect... I tried adding 

```
.menu {
  background-color: rgba(0,19,31) !important;
}
```

to userChrome.css as well but it didn't help. It's pretty baffling that it works on one distro and not another..

**Comment by killhellokitty** [comment]
I'm sorry, thats all I could think of that might be affecting it.  I am
considering installing Fedora on a partition to test it out and see if I
can't fix it.

**Comment by killhellokitty** [comment]
I hve installed fedora and and using delorean-3.16 theme with the chrome folder installed for firefox and this is an image of what I have.
![screenshot from 2015-05-22 17 58 43](https://cloud.githubusercontent.com/assets/9612437/7781031/abba58c6-00ac-11e5-8e2a-0bdd56064e11.png)

**Comment by aiguofer** [comment]
hmmm really strange, I tried creating a brand new user and installing DeLorean there and I still get the see through menus. I guess it must be some bug from upgrading Fedora. Did you download the Fedora 22 beta?

**Comment by killhellokitty** [comment]
Yes tested in Fedora 22 Beta.  Download the latest DeLorean version from
github and use the new chrome folder.  I think you will have better results.

**Comment by aiguofer** [comment]
Wooo!!! yeah that's awesome, thanks! :) It matches the nice blue to everything else too.

As far as the 'invisible' boxes, I'll add 

```
    border: 1px solid black;
```

to input, select, and textareas locally (in userContent.css), but might be something to consider.

I'll go ahead and close this.
